services:
  - type: web
    name: bot-whatsapp-zapatillas
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_MODEL
        value: meta-llama/llama-3.2-3b-instruct:free
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: WHATSAPP_VERIFY_TOKEN
        sync: false
      - key: RENDER_URL
        sync: false
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///tienda.db
